# Generated by Django 5.0.4 on 2024-05-09 00:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_dataabertas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataAbertas',
            new_name='DatasAbertas',
        ),
    ]
